build image

diff --git a/.github/workflows/e2e.yaml b/.github/workflows/e2e.yaml
--- a/.github/workflows/e2e.yaml
+++ b/.github/workflows/e2e.yaml
@@ -1,4 +1,4 @@
-name: e2e tests
+name: end-2-end Helm Chart Tests
 
 on:
   push:
@@ -22,17 +22,54 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v4
-      - name: Set up Go
-        uses: actions/setup-go@v5
-        with:
-          go-version-file: "go.mod"
 
-      - name: Install kind with registry
+      - name: ⚙️ Install kind with registry
         uses: bakito/kind-with-registry-action@main
         with:
           node_image: kindest/node:${{ matrix.k8s_version }}
           kubectl_version: ${{ matrix.k8s_version }}
 
-      - name: Install vault
+      - name: ⚙️ Install vault
+        run: ./testdata/e2e/vault-01-install.sh
+
+        # build image until vault is running
+      - name: 🖼 Build image
+        run: ./testdata/e2e/buildImage.sh
+
+      - name: ⚙️ Setup vault
+        run: ./testdata/e2e/vault-02-setup.sh
+
+      - name: ⚙️ Install vault unsealer
+        run: ./testdata/e2e/install-vault-unsealer.sh
+
+      - name: ✔️ Check vault
+        run: ./testdata/e2e/vault-03-check.sh
+        id: run_check_vault
+        # continue on error to show logs
+        continue-on-error: true
+
+      - name: 🪵 Print Pod logs
         run: |
-          ./testdata/setup-vault.sh
+          echo '```' >> $GITHUB_STEP_SUMMARY
+          echo '🔒 Vault 0 Pod logs' >> $GITHUB_STEP_SUMMARY
+          echo '```' >> $GITHUB_STEP_SUMMARY
+          kubectl logs -n vault vault-0 >> $GITHUB_STEP_SUMMARY
+          echo '```' >> $GITHUB_STEP_SUMMARY
+          echo '🔒 Vault 1 Pod logs' >> $GITHUB_STEP_SUMMARY
+          echo '```' >> $GITHUB_STEP_SUMMARY
+          kubectl logs -n vault vault-1 >> $GITHUB_STEP_SUMMARY
+          echo '```' >> $GITHUB_STEP_SUMMARY
+          echo '🔒 Vault 2 Pod logs' >> $GITHUB_STEP_SUMMARY
+          echo '```' >> $GITHUB_STEP_SUMMARY
+          kubectl logs -n vault vault-2 >> $GITHUB_STEP_SUMMARY
+          echo '```' >> $GITHUB_STEP_SUMMARY
+          echo '🪵 Unsealer Pod logs' >> $GITHUB_STEP_SUMMARY
+          echo '```' >> $GITHUB_STEP_SUMMARY
+          POD_NAME=$(kubectl get pod -n vault -l app.kubernetes.io/instance=vault-unsealer -o name)
+          kubectl logs -n vault ${POD_NAME} >> $GITHUB_STEP_SUMMARY
+
+      - name: 🔍 Fail if 'Check vault' failed
+        if: steps.run_check_vault.outcome=='failure'
+        run: |
+          echo "Step 'Check vault' failed: Check 'Print logs Unsealer' for errors"
+          exit 1
